config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 1, maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user.id)
  end

  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed in successfully."
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :password])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create #ここのローカルでもインスタンスでもいい
    book = Book.find(params[:book_id])
    #book_comment = BookComment.new(book_comment_params)
    #book_comment = current_user.book_comments.new(book_comment_params)
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back fallback_location: root_path
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back fallback_location: root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user.id)
    end
    @user = User.find(params[:id])
  end

  def update
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to books_path
    end
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_left.html.erb
<div class="container mt-1">
  <!-- ユーザーの詳細 -->
    <h2>User info</h2>
    <%= image_tag user.get_profile_image(100,100) %>
    <p>name：<%= user.name %></p>
    <p>Introduction：<%= user.introduction %></p>
    <%= link_to edit_user_path(@user.id), :method => :get do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
    <br>

  <!-- 新規投稿部分 -->
    <h2>New book</h2>
    <%= form_with model: book do |f| %>
      <h4>Title</h4>
        <%= f.text_field :title %>
      <h4>Opinion</h4>
        <%= f.text_area :body %>
      <div class='form-group'>
        <%= f.submit 'Create Book', class:'btn btn-sm btn-success' %>
      </div>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <h2>Editing Book</h2>
  </div>

  <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @book do |f| %>
  <div class="row">
    <div class="col col-2">
      <label for="inputName">Name</label>
    </div>
    <div class="col col-5">
      <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"name"%>
    </div>
  </div>

  <div class="row">
    <div class="col col-2">
      <label for="inputOpinion">Opinion</label>
    </div>
    <div class="col col-5">
      <%= f.text_field :body, autofocus: true, id:"inputBody", placeholder:"opinion"%>
    </div>
  </div>

  <div class="row">
    <div class='form-group'>
      <%= f.submit 'Update Book', class:'btn btn-sm btn-success' %>
    </div>
  </div>
  <% end %>

  <div class="row">
    <p><%= link_to "Show", book_path(@book.id) %></p>
    <p><%= link_to "Back", books_path %></p>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'left', book: @book, user: @user %>
    </div>


    <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>

    <!-- 投稿一覧 -->
    <div class="offset-md-1 col-md-8">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-2"></th>
            <th class="col-md-3">Title</th>
            <th class="col-md-3">Opinion</th>
            <th class="col-md-1"></th>
            <th class="col-md-3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td class="col-md-2">
                <%= link_to user_path(book.user_id) do %>
                  <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td class="col-md-3">
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td class="col-md-3">
                <%= book.body %>
              </td>
              <td class="col-md-1">
                <% if book.favorited_by?(current_user) %>
                  <!--%= link_to book_favorites_path(book.id), method: :delete do %>-->
                  <%= link_to book_favorites_path(book.id), method: :delete do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <!--%= link_to book_favorites_path(book.id), method: :post do %>-->
                  <%= link_to book_favorites_path(book.id), method: :post do %>
                    <i class="far fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                <% end %>
              </td>
              <td class="col-md-3">
                コメント数：<%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'left', book: @book, user: @user %>
    </div>

    <div class="offset-md-1 col-md-8">
      <div class="row">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td class="col-md-2">
                <%= image_tag @user.get_profile_image(100,100) %>
                <%= link_to @book.user.name, user_path(@book.user.id) %>
              </td>
              <td class="col-md-3"><%= link_to @book.title, book_path(@book.id) %></td>
              <td class="col-md-3"><%= @book.body %></td>
              <td class="col-md-1">
                <% if @book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(@book.id), method: :delete do %>
                    <i class="fas fa-heart"></i><%= @book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(@book.id), method: :post do %>
                    <i class="far fa-heart"></i><%= @book.favorites.count %>
                  <% end %>
                <% end %>
              </td>
              <td class="col-md-3">コメント数：<%= @book.book_comments.count %></td>
              <% if @book.user_id == current_user.id %>
                <td><%= link_to 'Edit', edit_book_path(@book.id), method: :get %></td>
                <td><%= link_to 'Destroy', book_path(@book.id), method: :delete %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>

      <% @book.book_comments.each do |book_comment| %>
        <div class="row">
          <div class="col-md-2">
            <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
            <%= link_to book_comment.user.name, user_path(book_comment.user_id) %>
          </div>
          <div class="col-md-3">
            <%= book_comment.comment %>
          </div>
          <div class="col-md-2">
            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
            <% end %>
          </div>
        </div>
      <% end %>

      <div class="row">
        <%= form_with model: [@book, @book_comment] do |f| %>
          <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>

      <% if @book_comment.errors.any? %>
        <%= @book_comment.errors.count %>件のエラーが発生しました
        <ul>
          <% @book_comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class="container mt-3">
  <div class="text-center">
    <h1>
      Welcome to <i class="fas fa-book"></i>Bookers !!
    </h1>
  <div>
</div>

app/views/homes/top.html.erb
<div class="container mt-3" style="text-align: center">
  <div>
    <body>
      <h1>Welcome to <i class="fas fa-book"></i>Bookers !!</h1>
      <p>
        In <i class="fas fa-book"></i>Bookers,<br>
        you can share and exchange your opinions , inpressions , and emotions<br>
        about various books!<br>
      </p>
      <div class="row">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-sm btn-primary" %>
      </div>
      <br>
      <div class="row">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-sm btn-success" %>
      </div>
    </body>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <script src="https://kit.fontawesome.com/8deba7ea7c.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FF9933">
        <div class="container">
          <!-- ロゴ部分 -->
          <a href="/" class="top_link">Bookers</a>
          <!-- ハンバーガーメニューの見た目 -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: "nav-link text-dark", method: :get do %>
                  　<i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: "nav-link text-dark", method: :get do %>
                  　<i class="fas fa-users"></i>Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: "nav-link text-dark", method: :get do %>
                  　<i class="fas fa-book-open"></i>Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, class: "nav-link text-dark", method: :delete do %>
                  　<i class="fas fa-sign-out-alt"></i>Log out
                  <% end %>
                </li>

              <% else %>
                <li class="nav-item">
                  <!--%= link_to root_path, class: "nav-link text-dark", method: :get do %-->
                  <%= link_to  root_path, class: "nav-link text-dark", method: :get do %>
                  　<i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path, class: "nav-link text-dark", method: :get do %>
                  　<i class="fas fa-link"></i>About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: "nav-link text-dark", method: :get do %>
                  　<i class="fas fa-user-plus"></i>Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: "nav-link text-dark", method: :get do %>
                  　<i class="fas fa-sign-in-alt"></i>Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="container">
        <%= flash[:notice] %>
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer>
      <div class="container mt-5">
        <p class="text-center">CopyRight Infratop.inc</p>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container mt-3">
  <div class="row">
    <h2>User info</h2>
  </div>

  <% if @user.errors.any? %>
    <%= @user.errors.count %>error prohibited this user from being updated:
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @user do |f| %>
  <div class="row">
    <label for="inputName">Name</label>
  </div>
  <div class="row">
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>
  </div>

  <div class="row">
    <label for="inputInformation">Introduction</label>
  </div>
  <div class="row">
    <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Intro"%>
  </div>

  <div class="row">
    <label for="inputImage">ProfileImage</label>
  </div>
  <div class="row">
    <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>
  </div>
  <br>

  <div class="row">
    <div class='form-group'>
      <%= f.submit 'Update User', class:'btn btn-sm btn-success' %>
    </div>
  </div>
  <% end %>

</div>

app/views/users/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/left', book: @book, user: @user %>
    </div>

    <div class="offset-md-1 col-md-8">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-2">Image</th>
            <th class="col-md-5">Name</th>
            <th class="col-md-5"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td class="col-md-2">
                <%= link_to user_path(user.id) do %>
                  <%= image_tag user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td class="col-md-5">
                <%= user.name %>
              </td>
              <td class="col-md-5">
                <%= link_to 'Show', user_path(user.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/left', book: @book_new, user: @user %>
    </div>

    <div class="offset-md-1 col-md-8">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-2"></th>
            <th class="col-md-3">Title</th>
            <th class="col-md-3">Opinion</th>
            <th class="col-md-1"></th>
            <th class="col-md-3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= image_tag @user.get_profile_image(100,100) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book_favorites_path(book.id), method: :delete do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                <% else %>
                  <%= link_to book_favorites_path(book.id), method: :post do %>
                    <i class="far fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                <% end %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>